export const documentationLinks = {
    nodeplace: [
        { id: 'nodeplace.json', name: 'nodeplace.json()' },
        { id: 'nodeplace.static', name: 'nodeplace.static()' },
        { id: 'nodeplace.urlencoded', name: 'nodeplace.urlencoded()' },
    ],
    application: [
        { id: 'app.all', name: 'app.all()' },
        { id: 'app.get', name: 'app.get()' },
        { id: 'app.listen', name: 'app.listen()' },
        { id: 'app.post', name: 'app.post()' },
        { id: 'app.put', name: 'app.put()' },
        // { id: 'app.patch', name: 'app.patch()' },
        { id: 'app.use', name: 'app.use()' },
    ],
    request: [
        { id: 'req.body', name: 'req.body' },
        // { id: 'req.cookies', name: 'req.cookies' },
        { id: 'req.params', name: 'req.params' },
        { id: 'req.query', name: 'req.query' },
        { id: 'req.res', name: 'req.res' },
    ],
    response: [
        { id: 'res.cookie', name: 'res.cookie()' },
        { id: 'res.clearCookie', name: 'res.clearCookie()' },
        { id: 'res.json', name: 'res.json()' },
        { id: 'res.send', name: 'res.send()' },
        { id: 'res.sendFile', name: 'res.sendFile()' },
        { id: 'res.set', name: 'res.set()' },
        { id: 'res.status', name: 'res.status()' },
        { id: 'res.type', name: 'res.type()' },
    ],
    router: [
        { id: 'router.route', name: 'router.route()' },
        { id: 'router.delete', name: 'router.delete()' },
        { id: 'router.get', name: 'router.get()' },
        { id: 'router.patch', name: 'router.patch()' },
        { id: 'router.post', name: 'router.post()' },
        { id: 'router.put', name: 'router.put()' },
    ],
}